services:
  item-service:
    container_name: item-service
    build:
      context: ./service/item-service
      dockerfile: ./build/docker/Dockerfile
    environment:
      - ITEM_SERVICE_PORT
    ports:
      - "${ITEM_SERVICE_PORT}:${ITEM_SERVICE_PORT}"
    healthcheck:
      test: ["CMD", "/usr/bin/wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${ITEM_SERVICE_PORT}/healthz"]
      interval: 10s
      timeout: 10s
      retries: 3
    depends_on:
      opentelemetry-collector:
        condition: service_started
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:0.79.0
    container_name: opentelemetry-collector
    restart: always
    command: ["--config=/etc/config.yaml"]
    volumes:
      - ./config/opentelemetry-collector/config.yaml:/etc/config.yaml
    ports:
      - "${OPEN_TELEMETRY_GRPC_PORT}:4318"
