global:
  evaluation_interval: 15s
  scrape_interval: 10s
scrape_configs:
- job_name: otel
  honor_labels: true
  static_configs:
  - targets:
    - 'opentelemetry-collector:9464'
- job_name: otel-collector
  static_configs:
  - targets:
    - 'opentelemetry-collector:8888'
